### ISSUE TITLE
Pre-commit or pre-push hook

### ISSUE THREAD

**Issue by agustito37** [rootstrap/react-native-use-styles#6]
# Feature Requests

### Checklist

- [x] My feature request is specific to `@rootstrap/react-native-use-styles`.

- [x] I've searched open issues to make sure I'm not opening a duplicate feature request

### Description

We should run a linter and the tests before pushing it to the repository. Having a pre-commit or pre-push hook would be great.

**Comment by lmajhi** [comment]
I would like take up this issue, during Hacktoberfest.

**Comment by agustito37** [comment]
Hi @lmajhi , of course, go ahead. If you have any questions just ask.

**Comment by agustito37** [comment]
Let me know when you start working on this ps.

**Comment by lmajhi** [comment]
I plan to work on this coming Saturday(03, October, IST).
My assumptions,
1) I'll be creating a pre-push hook, which is executed before the code is pushed to remote branch.
2) The hook will run the test-runner, jest in our case.
3) Since i dont see a linter in **package.json**, **scripts** i'll added one in package.json, and the hook shall run the same.

Is there anything else, that I should be mindful of?

**Comment by agustito37** [comment]
I think that's it, thanks for the update. Yes, we need to add a script to run the linter; we have eslint and prettier configured thought.

**Comment by lmajhi** [comment]
@agustito37 : Can you provide me permission to collaborate on this project. I'm getting 403 error while pushing a new branch. Thanks.

**Comment by agustito37** [comment]
Hi @Imajhi, the process of contributing to this repo is through a forked repository. So you'll need to create a fork of this repo, and from that fork, create a PR that solves this issue. You can see an example here: https://github.com/rootstrap/react-native-use-styles/pull/11
If you have any problems, please let me know.

**Comment by lmajhi** [comment]
@agustito37 : The PR is up, please provide feedback, if any.
